### ISSUE TITLE
Question - Get related children

### ISSUE THREAD

**Issue by felixhagspiel** [getkirby/kql#26]
I have a `product` that can have one `case`. A `case` can have multiple `products`.

Pulling the `case` inside a `product` is working fine, but now I need to query all `products` for a  `case`.

This is my `product.yml` blueprint:

```
    fields:
      case:
        label: Case
        type: pages
        query: site.find('cases')
        multiple: false
        translate: false
```

Inside my `case.yml` I have not specified any relation.

How would I do this? As I have no relation specified in a `case` I am not sure what the best (kirby) way is to accomplish this. I found this: https://getkirby.com/docs/cookbook/content/filtering#filtering-by-the-pages-files-or-users-field

```
$page->children()->filter(function($child) use($page) {
    return $child->related()->toPages()->has($page);
});
```

but as I am not sure how I would write this in dot-notation or KQL.
