### ISSUE TITLE
how to select and transform data from structures

### ISSUE THREAD

**Issue by bnomei** [getkirby/kql#8]
i tried field.toArray and field.toStructure combined with arrayItem and structureItem like in query language but that did not work. best i could find out was to use field.yaml or a custom pagemethod. 

i would love to see support for arrayItem and structureItem in kql since that would be most consistent imho.

**Comment by kms-rscholz** [comment]
```
{
    "query": "page('guides/print/business-materials').children",
    "select": {
        "url": true,
        "title": true,
        "id": true,
        "slides": {
            "query": "page.slides.toStructure",
            "select": {
                "image": {
                    "query": "structureItem.image.toFile",
                    "select": {
                    	"url": true,
                    	"srcset": "file.srcset([300, 800, 1024])"
                    }
                },
                "description" : "structureItem.description"
            }
        }
    },
    "pagination": {
        "limit": 10
    }
}
```

This works for me

**Comment by bnomei** [comment]
thanks @kms-rscholz
i tried something similar but must have made an error somewhere.

**Comment by bnomei** [comment]
i can not get it to work.

```yml
        fields:
          action:
            label: Aktionen
            type: structure
            fields:
              link:
                type: text
                required: true
              title:
                type: text
                required: true
```

```json
{
  "query": "page('somepage')",
  "select": {
    "actions": {
      "query": "page.action.toStructure",
      "select": {
        "link": "structureItem.link",
        "title": "structureItem.title"
      }
    }
  }
}
```

**Comment by bnomei** [comment]
```yml
"actions": {
      "query": "page.action.toStructure",
      "select": {
        "link": true,
        "title": true
      }
    }
```

does work. but it seems to me `structureItem` does not.
